name: iOS CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
        
    - name: Install SwiftLint
      run: |
        brew install swiftlint
        
    - name: SwiftLint
      run: |
        swiftlint lint Plantdoc-app/ --reporter github-actions-logging || true
        
    - name: Check for TODO comments
      run: |
        if grep -r "TODO\|FIXME\|HACK" Plantdoc-app/ --include="*.swift"; then
          echo "Found TODO/FIXME/HACK comments in code"
          exit 1
        fi
        
    - name: Check file size
      run: |
        # Check if any Swift file is larger than 1000 lines
        for file in $(find Plantdoc-app/ -name "*.swift"); do
          lines=$(wc -l < "$file")
          if [ $lines -gt 1000 ]; then
            echo "Warning: $file has $lines lines (consider splitting)"
          fi
        done

  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run security scan
      run: |
        # Check for hardcoded secrets
        if grep -r "password\|secret\|key\|token" Plantdoc-app/ --include="*.swift" --include="*.plist" | grep -v "//"; then
          echo "Warning: Potential hardcoded secrets found"
        fi
        
        # Check for insecure network calls
        if grep -r "http://" Plantdoc-app/ --include="*.swift"; then
          echo "Warning: Insecure HTTP calls found"
        fi 